Created Job and Job Application
DragosGhinea/HiringSystem pull request #8
Opened 2023-04-15 20:49 UTC by stefaniarincu

Also modified CandidateUser to map the associative table JobApplication

2023-04-15 21:17 UTC, DragosGhinea requested changes

2023-04-15 21:17 UTC, DragosGhinea commented on src/main/java/ro/hiringsystem/model/JobApplication.java
> +@Table(name="\"JOB_APPLICATION\"")
Same thing as for the jobs table

2023-04-15 21:17 UTC, DragosGhinea commented on src/main/java/ro/hiringsystem/service/JobApplicationService.java
> +    void updateElementById(JobApplicationDto newJobApplicationDto);
This method has been renamed to saveElement in the Spring Security pull request and saves the user to database no matter if it was already in there or not, please update it here as well so there are no merging conflicts

2023-04-15 21:17 UTC, DragosGhinea commented on src/main/java/ro/hiringsystem/service/JobService.java
> +    void updateElementById(JobDto newJobDto);
Same comment as the one left in JobApplicationService

2023-04-15 21:17 UTC, DragosGhinea commented on src/main/java/ro/hiringsystem/service/impl/JobApplicationServiceImpl.java
> +        if(jobApplication.isEmpty()) {
So as mentioned, please do not throw an error and just save the user

2023-04-15 21:17 UTC, DragosGhinea commented on src/main/java/ro/hiringsystem/service/impl/JobServiceImpl.java
> +            throw new RuntimeException("Job not found!");
Same comment as in JobApplicationServiceImpl

2023-04-16 08:45 UTC, DafinaTrufas requested changes

2023-04-16 08:45 UTC, DafinaTrufas commented on src/main/java/ro/hiringsystem/mapper/JobApplicationMapper.java
> +    @Mapping(source = "candidateUser", target = "candidateUser")
These @Mapping annotation here are redundant, since the fields are implicitly mapped that way. So I think you could remove them.

2023-04-16 15:42 UTC, DafinaTrufas approved these changes

2023-04-16 16:39 UTC, DragosGhinea approved these changes

2023-04-16 17:06 UTC, CoCodrilo1710 approved these changes

2023-04-16 17:08 UTC, merged